/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package uasaplikasisederhana;


import java.util.LinkedList;
import java.util.Queue;
import javax.swing.JOptionPane;
import java.util.ArrayList;
/**
 *
 * @author IdeaPad
 */
public class AplikasiSederhana_Antrian extends javax.swing.JFrame {

    /**
     * Creates new form ParkirJFrame
     */
     Queue<Object> antrian = new LinkedList<>();
    int nomor = 0;
    
    public ArrayList tujuan = new ArrayList();
    public ArrayList ruang = new ArrayList();
    public AplikasiSederhana_Antrian() {
        initComponents();
        inisialisasi();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    private void inisialisasi(){
        lbJmlAntrian.setText("0");
        txtTotalAntrian.setText("0");
        lbPanggilanAntrian.setText("-----");
        
        txtatas1.setText("DATA ANTRIAN VAKSINASI KECAMATAN TAMPAN");
        txtatas2.setText("PEKANBARU");
        txtatas3.setText("Jl.Kamboja No.110, Simpang Baru, Kec.Tampan");
        txtatas4.setText("Sabtu, 19 Juni 2021");
        txtatas5.setText("Nomor Antrian");
        txtatas6.setText("--------------");
        txtatas7.setText("Silahkan Menunggu");
        txtatas8.setText("--------------");
    }
    
   
    private void Antrian(){
        // ini berguna untuk menambahkan fitur fungsi untuk tambahAntrian button   
        
        nomor++;//tambah nomornya disini
        String Antrian = "Antrian "+ nomor; //save dalam variabel antr
        antrian.add(Antrian); //menambahkan antriannya ke list
        String cvt = String.valueOf(antrian.size()); //mengambil panjangnya list
        lbJmlAntrian.setText(cvt); //mengsetting text komponen agar menampilkan panjang list
        lbPanggilanAntrian.setText(""+antrian.peek()); // untuk menampilkan data yang paling atas
        txtTotalAntrian.setText(""+nomor); //agar tampilan total antrian keliar outputnya
        txtAntrian.append(Antrian +  "\n");
        
        txtatas4.setText(" Senin, 28 Juni 2021");
        txtatas5.setText(" Nomor Antrian");
        txtatas6.setText(" " + nomor);
        txtatas7.setText(" Silahkan Menunggu " +  cvt  + " Antrian Lagi");
        txtatas8.setText(" Mohon Untuk Bersabar");
    }
    
    private void ProsesAntrian(){
       if(antrian.isEmpty()){ // jika antrian tidak ada
            JOptionPane.showMessageDialog(this, "Ambil Nomor antriannya dahulu!");
        }
        txtAntrian.setText(""); // mengosongkan textarea list antrian
        antrian.poll(); // mengambil antrian
        antrian.forEach((Object element) -> { 
            txtAntrian.append("" + element + "\n"); // print semua antrian ke textarea list
        });
        if(antrian.isEmpty()){
            lbPanggilanAntrian.setText("-----");
        }else{
            lbPanggilanAntrian.setText(""+antrian.peek());
        }
    }
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAntrian = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        lbjmlAntrian = new javax.swing.JLabel();
        lbTotalAntrian = new javax.swing.JLabel();
        PanggilanAntrian = new javax.swing.JLabel();
        btnProsesAntrian = new javax.swing.JButton();
        btnAmbilNomorAntrian = new javax.swing.JButton();
        lbJmlAntrian = new javax.swing.JLabel();
        txtTotalAntrian = new javax.swing.JLabel();
        lbPanggilanAntrian = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txtatas1 = new javax.swing.JLabel();
        txtatas2 = new javax.swing.JLabel();
        txtatas3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        txtatas4 = new javax.swing.JLabel();
        txtatas5 = new javax.swing.JLabel();
        txtatas6 = new javax.swing.JLabel();
        txtatas7 = new javax.swing.JLabel();
        txtatas8 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 204));

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Daftar Antrian");

        txtAntrian.setBackground(new java.awt.Color(102, 102, 102));
        txtAntrian.setColumns(20);
        txtAntrian.setForeground(new java.awt.Color(255, 255, 255));
        txtAntrian.setRows(5);
        jScrollPane1.setViewportView(txtAntrian);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel1)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(0, 0, 102));

        lbjmlAntrian.setFont(new java.awt.Font("Arial Black", 0, 13)); // NOI18N
        lbjmlAntrian.setForeground(new java.awt.Color(255, 255, 255));
        lbjmlAntrian.setText("Jumlah Antrian");
        lbjmlAntrian.setToolTipText("");

        lbTotalAntrian.setFont(new java.awt.Font("Arial Black", 0, 13)); // NOI18N
        lbTotalAntrian.setForeground(new java.awt.Color(255, 255, 255));
        lbTotalAntrian.setText("Total Antrian");

        PanggilanAntrian.setFont(new java.awt.Font("Arial Black", 0, 13)); // NOI18N
        PanggilanAntrian.setForeground(new java.awt.Color(255, 255, 255));
        PanggilanAntrian.setText("Panggilan Nomor Antrian");

        btnProsesAntrian.setBackground(new java.awt.Color(255, 0, 0));
        btnProsesAntrian.setFont(new java.awt.Font("Arial Black", 0, 13)); // NOI18N
        btnProsesAntrian.setForeground(new java.awt.Color(255, 255, 255));
        btnProsesAntrian.setText("Proses Antrian");
        btnProsesAntrian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProsesAntrianActionPerformed(evt);
            }
        });

        btnAmbilNomorAntrian.setBackground(new java.awt.Color(255, 0, 0));
        btnAmbilNomorAntrian.setFont(new java.awt.Font("Arial Black", 0, 13)); // NOI18N
        btnAmbilNomorAntrian.setForeground(new java.awt.Color(255, 255, 255));
        btnAmbilNomorAntrian.setText("Ambil Nomor Antrian");
        btnAmbilNomorAntrian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAmbilNomorAntrianActionPerformed(evt);
            }
        });

        lbJmlAntrian.setFont(new java.awt.Font("Arial Black", 0, 50)); // NOI18N
        lbJmlAntrian.setForeground(new java.awt.Color(255, 255, 255));
        lbJmlAntrian.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbJmlAntrian.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtTotalAntrian.setFont(new java.awt.Font("Arial Black", 0, 50)); // NOI18N
        txtTotalAntrian.setForeground(new java.awt.Color(255, 255, 255));
        txtTotalAntrian.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtTotalAntrian.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lbPanggilanAntrian.setFont(new java.awt.Font("Arial Black", 0, 25)); // NOI18N
        lbPanggilanAntrian.setForeground(new java.awt.Color(255, 255, 255));
        lbPanggilanAntrian.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbPanggilanAntrian.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel8.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("DATA ANTRIAN VAKSINASI KECAMATAN TAMPAN");

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));

        txtatas1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        txtatas1.setForeground(new java.awt.Color(255, 255, 255));
        txtatas1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtatas1.setToolTipText("");
        txtatas1.setFocusable(false);
        txtatas1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        txtatas2.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        txtatas2.setForeground(new java.awt.Color(255, 255, 255));
        txtatas2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        txtatas3.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        txtatas3.setForeground(new java.awt.Color(255, 255, 255));
        txtatas3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtatas3.setText("     ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtatas1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(txtatas2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(txtatas3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(txtatas1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtatas2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtatas3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 14, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(102, 102, 102));

        txtatas4.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        txtatas4.setForeground(new java.awt.Color(255, 255, 255));
        txtatas4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        txtatas5.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        txtatas5.setForeground(new java.awt.Color(255, 255, 255));
        txtatas5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        txtatas6.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        txtatas6.setForeground(new java.awt.Color(255, 255, 255));
        txtatas6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        txtatas7.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        txtatas7.setForeground(new java.awt.Color(255, 255, 255));
        txtatas7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtatas7.setToolTipText("");

        txtatas8.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        txtatas8.setForeground(new java.awt.Color(255, 255, 255));
        txtatas8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtatas4, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)
            .addComponent(txtatas5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(txtatas6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(txtatas7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(txtatas8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(txtatas4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtatas5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtatas6, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtatas7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtatas8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel18.setFont(new java.awt.Font("Arial Black", 0, 13)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Mesin Antrian");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(lbJmlAntrian, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addComponent(txtTotalAntrian, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addComponent(lbjmlAntrian)
                                .addGap(108, 108, 108)
                                .addComponent(lbTotalAntrian)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(168, 168, 168)
                                .addComponent(btnAmbilNomorAntrian, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 85, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGap(140, 140, 140)
                                .addComponent(btnProsesAntrian))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGap(122, 122, 122)
                                .addComponent(PanggilanAntrian))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addComponent(lbPanggilanAntrian, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGap(239, 239, 239)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(38, 38, 38))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel18)
                .addGap(169, 169, 169))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbjmlAntrian)
                            .addComponent(lbTotalAntrian))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbJmlAntrian, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTotalAntrian, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(80, 80, 80)
                        .addComponent(PanggilanAntrian)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbPanggilanAntrian, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnProsesAntrian, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                        .addGap(58, 58, 58))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnAmbilNomorAntrian, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProsesAntrianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProsesAntrianActionPerformed
        ProsesAntrian();
    }//GEN-LAST:event_btnProsesAntrianActionPerformed

    private void btnAmbilNomorAntrianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAmbilNomorAntrianActionPerformed
        Antrian ();
    }//GEN-LAST:event_btnAmbilNomorAntrianActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AplikasiSederhana_Antrian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AplikasiSederhana_Antrian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AplikasiSederhana_Antrian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AplikasiSederhana_Antrian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new AplikasiSederhana_Antrian().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel PanggilanAntrian;
    private javax.swing.JButton btnAmbilNomorAntrian;
    private javax.swing.JButton btnProsesAntrian;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbJmlAntrian;
    private javax.swing.JLabel lbPanggilanAntrian;
    private javax.swing.JLabel lbTotalAntrian;
    private javax.swing.JLabel lbjmlAntrian;
    private javax.swing.JTextArea txtAntrian;
    private javax.swing.JLabel txtTotalAntrian;
    private javax.swing.JLabel txtatas1;
    private javax.swing.JLabel txtatas2;
    private javax.swing.JLabel txtatas3;
    private javax.swing.JLabel txtatas4;
    private javax.swing.JLabel txtatas5;
    private javax.swing.JLabel txtatas6;
    private javax.swing.JLabel txtatas7;
    private javax.swing.JLabel txtatas8;
    // End of variables declaration//GEN-END:variables

}
